### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by LucasRocha-01** [SoftwareBrothers/adminjs-fastify#17]
i don't know what to do about this error

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in C:\Users\rocha\Documents\Projetos\EZ-Shorturl\node_modules\@adminjs\fastify\package.json
    at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
    at new NodeError (node:internal/errors:405:5)
    at exportsNotFound (node:internal/modules/esm/resolve:359:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:639:13)
    at resolveExports (node:internal/modules/cjs/loader:567:36)
    at Module._findPath (node:internal/modules/cjs/loader:636:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1063:27)
    at u.default._resolveFilename (C:\Users\rocha\Documents\Projetos\EZ-Shorturl\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:1519)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AdminJS (c:\Users\rocha\Documents\Projetos\EZ-Shorturl\src\view\index.js:1:33)
    at Object.<anonymous> (c:\Users\rocha\Documents\Projetos\EZ-Shorturl\src\view\index.js:26:7)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.F (C:\Users\rocha\Documents\Projetos\EZ-Shorturl\node_modules\@esbuild-kit\cjs-loader\dist\index.js:1:941)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.17.1

**Comment by LucasRocha-01** [comment]
solved by including "type":"module" in package.json
